# Generated by Django 5.2.14 on 2026-05-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('required_spec_keys', models.CharField(blank=True, help_text='Pisahkan dengan koma. Contoh: Processor, RAM, SSD', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Contoh: fa-laptop', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField()),
                ('specifications', models.JSONField(blank=True, default=dict, null=True)),
                ('price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(blank=True, default=0, null=True)),
                ('garansi', models.CharField(choices=[('NW', 'Tanpa Garansi'), ('1', '1 Bulan'), ('3', '3 Bulan'), ('6', '6 Bulan'), ('1YD', '1 Tahun Dist'), ('1YR', '1 Tahun Resmi')], default='1', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'Baru / Brand New'), ('A', 'Second Grade A'), ('AA', 'Second Grade AA'), ('AA+', 'Second Grade AA+'), ('AAA+', 'Second Grade AAA+')], default='AA+', max_length=5)),
                ('is_sale', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='katalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='katalog.product')),
            ],
        ),
    ]
