# Generated by Django 5.2.14 on 2026-05-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
    ]
