# Generated by Django 5.2.14 on 2026-05-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_alter_category_options_remove_product_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garansi',
            field=models.CharField(choices=[('NW', 'Tanpa Garansi'), ('1', '1 Bulan'), ('3', '3 Bulan'), ('6', '6 Bulan'), ('1YD', '1 Tahun Dist'), ('1YR', '1 Tahun Resmi')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
