# Generated by Django 5.2.14 on 2026-05-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_product_garansi_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='required_spec_keys',
            field=models.CharField(blank=True, help_text='Pisahkan dengan koma. Contoh: Processor, RAM, SSD', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
