# Generated by Django 5.2.14 on 2026-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0007_category_required_spec_keys_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
