# Generated by Django 5.2.14 on 2026-05-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0008_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Baru / Brand New'), ('A', 'Second Grade A'), ('AA', 'Second Grade AA'), ('AA++', 'Second Grade AA+')], default='AA+', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
