# Generated by Django 5.2.14 on 2026-05-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0009_alter_product_condition_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Baru / Brand New'), ('A', 'Second Grade A'), ('AA', 'Second Grade AA'), ('AA+', 'Second Grade AA+'), ('AAA+', 'Second Grade AAA+')], default='AA+', max_length=5),
        ),
    ]
